### ISSUE TITLE
yolov3  with OpenCVSharp 3.4.1

### ISSUE THREAD

**Issue by ffrankozz** [died/OpenCvSharpDnnYolo#1]
Hi died,
Have you tried YOLOv3 with OpenCVSharp 3.4.1? My experiment is not successful.

**Comment by died** [comment]
@frank-ozgul not yet, I can find time to test it, if success I will let you know.

**Comment by ffrankozz** [comment]
In Python and C++ implementations, I see that they  use a method  called  like "Net.GetUnconnectedLayers()  meaning output layers and place the string array in net.Forward() call as a parameter.
With OpenCVSharp we do not have such a method. Perhaps  we can extract them from layer names. But we need to know which layers are output layers.

**Comment by died** [comment]
@frank-ozgul  you can check this [YOLO3-With-OpenCvSharp4](https://github.com/died/YOLO3-With-OpenCvSharp4)
