### ISSUE TITLE
Exception thrown during operation

### ISSUE THREAD

**Issue by valavakilian** [died/OpenCvSharpDnnYolo#2]
Hi and thanks a lot for sharing your code. I'm trying to run a project similar to yours. I am testing out with your code and I run into a exception.
at:
 var org = Cv2.ImRead(file);
this is the exception: 
System.TypeInitializationException: 'The type initializer for 'OpenCvSharp.NativeMethods' threw an exception.'
Inner Exception
DllNotFoundException: Unable to load DLL 'OpenCvSharpExtern': The specified module could not be found. (Exception from HRESULT: 0x8007007E)

thank you

**Comment by valavakilian** [comment]
Hi. Sorry to ask again but I was able to get rid of that exception and now I run into : System.ArgumentException: 'Cannot marshal: Encountered unmappable character.'
at:
System.ArgumentException: 'Cannot marshal: Encountered unmappable character.'

**Comment by died** [comment]
@valavakilian maybe you can try yolo v3 with opencvsharp4 , I have a demo here [YOLO3-With-OpenCvSharp4](https://github.com/died/YOLO3-With-OpenCvSharp4) , it can solve your first question, I am not sure 2nd question but you can try opencvsharp4 first.
