### ISSUE TITLE
How can i use GPU in this project to increase the speed 

### ISSUE THREAD

**Issue by 16Huzeyu** [died/OpenCvSharpDnnYolo#4]
HELLO died，your project help me a lot. But the speed is a liitle slow ,and I notice that it don't use GPU to calculate.So I want to ask for help ,how can i use GPU in this project to increase the speed .
Thank you very much

**Comment by 16Huzeyu** [comment]
HELLO died，your project help me a lot. But the speed is a liitle slow ,and I notice that it don't use GPU to calculate.So I want to ask for help ,how can i use GPU in this project to increase the speed .
Thank you very much

**Comment by died** [comment]
@16Huzeyu you can try build OpenCvSharp with GPU enable by yourself....
